package com.example.data

import kotlin.math.max
import kotlin.math.min
import kotlin.random.Random

/**
 * Enemy combat action type generated by the AI decision script.
 */
enum class EnemyActionType {
    ATTACK,       // Direct attack on player
    HEAL,         // Repair core integrity / shield recovery when health is critical
    HACK_PLAYER,  // Cyber-exploit draining player RAM and damaging shields
    FORTIFY_ICE   // Rebuild ICE shield firewall
}

/**
 * Proximity classification between enemy unit and player runner.
 */
enum class CombatProximity {
    MELEE_CLOSE,   // Distance 1: High chance of heavy physical attack or close range hack
    MEDIUM_RANGE,  // Distance 2-3: Balanced tactical distance for hacks & ranged attacks
    LONG_RANGE     // Distance 4+: Long range hacks, ICE fortification, or repair
}

/**
 * Decision payload output from the AI behavior script.
 */
data class EnemyAIDecision(
    val actionType: EnemyActionType,
    val actionName: String,
    val damage: Int = 0,
    val healAmount: Int = 0,
    val shieldAmount: Int = 0,
    val ramDrain: Int = 0,
    val logMessage: String = ""
)

    /**
     * Boss-specific AI evaluation. Called when the enemy is a boss.
     */
    fun evaluateBossAction(
        boss: Enemy,
        playerHealth: Int,
        playerMaxHealth: Int,
        playerRam: Int
    ): EnemyAIDecision {
        val healthRatio = boss.integrity.toFloat() / boss.maxIntegrity.coerceAtLeast(1)
        val shieldRatio = boss.shield.toFloat() / boss.maxShield.coerceAtLeast(1)
        val turn = boss.turnCounter

        return when (boss.bossType) {
            BossType.FIREWALL_SENTINEL -> evaluateSentinel(boss, healthRatio, shieldRatio, turn, playerHealth, playerRam)
            BossType.DAEMON_OVERLORD -> evaluateOverlord(boss, healthRatio, shieldRatio, turn, playerHealth, playerRam)
            BossType.BLACK_ICE_COLOSSUS -> evaluateColossus(boss, healthRatio, shieldRatio, turn, playerHealth, playerMaxHealth, playerRam)
            null -> evaluateAction(boss.integrity, boss.maxIntegrity, boss.shield, boss.maxShield, boss.damage, playerHealth, playerRam)
        }
    }

    private fun evaluateSentinel(boss: Enemy, healthRatio: Float, shieldRatio: Float, turn: Int, playerHealth: Int, playerRam: Int): EnemyAIDecision {
        // Phase 2 at 50% HP: gains counter-attack ability
        if (healthRatio < 0.50f && boss.bossPhase == 1) {
            boss.bossPhase = 2
            return EnemyAIDecision(
                actionType = EnemyActionType.FORTIFY_ICE,
                actionName = "FIREWALL OVERCLOCK",
                shieldAmount = (boss.maxShield * 0.4f).toInt(),
                logMessage = "🔥 SENTINEL PHASE 2: Firewall Sentinel activated counter-intrusion protocols! Shield restored +${(boss.maxShield * 0.4f).toInt()}! All attacks now reflect 50% damage!"
            )
        }

        // Every 3 turns: shield regeneration
        if (turn % 3 == 0 && shieldRatio < 0.80f) {
            val restore = (boss.maxShield * 0.35f).toInt()
            return EnemyAIDecision(
                actionType = EnemyActionType.FORTIFY_ICE,
                actionName = "ICE Shield Reboot",
                shieldAmount = restore,
                logMessage = "🛡️ SENTINEL REBOOT: Firewall Sentinel restored $restore shield integrity!"
            )
        }

        // Every 5 turns: system lockdown (stun)
        if (turn % 5 == 0) {
            return EnemyAIDecision(
                actionType = EnemyActionType.HACK_PLAYER,
                actionName = "System Lockdown",
                damage = boss.damage,
                ramDrain = 2,
                logMessage = "🔒 LOCKDOWN: Firewall Sentinel initiated system lockdown! Player stunned for 1 turn! $boss.damage damage + 2 RAM drained!"
            )
        }

        // Default: heavy attack
        val dmg = boss.damage + Random.nextInt(-2, 6)
        return EnemyAIDecision(
            actionType = EnemyActionType.ATTACK,
            actionName = "Sentinel Strike",
            damage = max(5, dmg),
            logMessage = "🚨 SENTINEL STRIKE: Firewall Sentinel unleashed heavy counter-intrusion blast for $dmg damage!"
        )
    }

    private fun evaluateOverlord(boss: Enemy, healthRatio: Float, shieldRatio: Float, turn: Int, playerHealth: Int, playerRam: Int): EnemyAIDecision {
        // Phase 2 at 60% HP: summon daemons
        if (healthRatio < 0.60f && boss.bossPhase == 1) {
            boss.bossPhase = 2
            return EnemyAIDecision(
                actionType = EnemyActionType.HEAL,
                actionName = "Summon Daemon",
                healAmount = (boss.maxIntegrity * 0.2f).toInt(),
                logMessage = "👹 OVERLORD SUMMON: Daemon Overlord summoned a lesser daemon to aid in combat! Healed +${(boss.maxIntegrity * 0.2f).toInt()} HP!"
            )
        }

        // Phase 3 at 30% HP: massive RAM drain
        if (healthRatio < 0.30f && boss.bossPhase == 2) {
            boss.bossPhase = 3
            return EnemyAIDecision(
                actionType = EnemyActionType.HACK_PLAYER,
                actionName = "Neural Devour",
                damage = boss.damage + 15,
                ramDrain = min(5, playerRam),
                logMessage = "💀 OVERLORD PHASE 3: Daemon Overlord unleashed Neural Devour! ${boss.damage + 15} damage + ${min(5, playerRam)} RAM DRAINED!"
            )
        }

        // Every 4 turns: RAM drain
        if (turn % 4 == 0 && playerRam > 0) {
            val drain = min(4, playerRam)
            return EnemyAIDecision(
                actionType = EnemyActionType.HACK_PLAYER,
                actionName = "RAM Siphon",
                damage = boss.damage / 2,
                ramDrain = drain,
                logMessage = "⚡ RAM SIPHON: Daemon Overlord drained $drain MB RAM + ${(boss.damage / 2)} damage!"
            )
        }

        // 30% chance: shadow step (dodge hint)
        if (Random.nextInt(100) < 30) {
            return EnemyAIDecision(
                actionType = EnemyActionType.ATTACK,
                actionName = "Shadow Step Strike",
                damage = boss.damage + Random.nextInt(5, 12),
                logMessage = "👤 SHADOW STEP: Daemon Overlord phased through defenses for ${boss.damage + Random.nextInt(5, 12)} damage!"
            )
        }

        // Default: heavy attack
        val dmg = boss.damage + Random.nextInt(-2, 5)
        return EnemyAIDecision(
            actionType = EnemyActionType.ATTACK,
            actionName = "Overlord Assault",
            damage = max(6, dmg),
            logMessage = "👹 OVERLORD ASSAULT: Daemon Overlord attacked for $dmg damage!"
        )
    }

    private fun evaluateColossus(boss: Enemy, healthRatio: Float, shieldRatio: Float, turn: Int, playerHealth: Int, playerMaxHealth: Int, playerRam: Int): EnemyAIDecision {
        // Phase 2 at 65% HP: adaptive armor
        if (healthRatio < 0.65f && boss.bossPhase == 1) {
            boss.bossPhase = 2
            return EnemyAIDecision(
                actionType = EnemyActionType.FORTIFY_ICE,
                actionName = "Adaptive Plating",
                shieldAmount = (boss.maxShield * 0.5f).toInt(),
                logMessage = "🔷 COLOSSUS PHASE 2: Black ICE Colossus activated adaptive plating! Shield +${(boss.maxShield * 0.5f).toInt()}! Incoming damage reduced by 25%!"
            )
        }

        // Phase 3 at 35% HP: neural storm
        if (healthRatio < 0.35f && boss.bossPhase == 2) {
            boss.bossPhase = 3
            return EnemyAIDecision(
                actionType = EnemyActionType.HACK_PLAYER,
                actionName = "Neural Storm",
                damage = boss.damage + 20,
                ramDrain = min(4, playerRam),
                logMessage = "⚡ NEURAL STORM: Black ICE Colossus unleashed devastating neural storm! ${boss.damage + 20} damage + ${min(4, playerRam)} RAM DRAINED!"
            )
        }

        // Every 3 turns: phase shift (becomes harder to hit)
        if (turn % 3 == 0) {
            return EnemyAIDecision(
                actionType = EnemyActionType.ATTACK,
                actionName = "Phase Shift Strike",
                damage = boss.damage + Random.nextInt(8, 18),
                logMessage = "🌀 PHASE SHIFT: Black ICE Colossus phased through reality for ${boss.damage + Random.nextInt(8, 18)} devastating damage!"
            )
        }

        // 25% chance: heal
        if (Random.nextInt(100) < 25 && healthRatio < 0.70f) {
            val heal = (boss.maxIntegrity * 0.15f).toInt()
            return EnemyAIDecision(
                actionType = EnemyActionType.HEAL,
                actionName = "Core Reboot",
                healAmount = heal,
                logMessage = "🔧 CORE REBOOT: Black ICE Colossus restored $heal HP!"
            )
        }

        // Default: massive attack
        val dmg = boss.damage + Random.nextInt(-2, 8)
        return EnemyAIDecision(
            actionType = EnemyActionType.ATTACK,
            actionName = "Colossus Slam",
            damage = max(8, dmg),
            logMessage = "🔴 COLOSSUS SLAM: Black ICE Colossus crushed down for $dmg damage!"
        )
    }
}
object EnemyCombatAIScript {

    /**
     * Determines combat decision based on current health, proximity distance, and player status.
     *
     * @param enemyHealth Current enemy health points
     * @param enemyMaxHealth Maximum enemy health points
     * @param enemyShield Current enemy shield points
     * @param enemyMaxShield Maximum enemy shield points
     * @param enemyBaseDamage Base damage capability of enemy
     * @param playerHealth Current player health points
     * @param playerRam Current player available RAM
     * @param proximityDistance Sub-grid distance between enemy and player (default 1)
     */
    fun evaluateAction(
        enemyHealth: Int,
        enemyMaxHealth: Int,
        enemyShield: Int,
        enemyMaxShield: Int,
        enemyBaseDamage: Int,
        playerHealth: Int,
        playerRam: Int,
        proximityDistance: Int = 1
    ): EnemyAIDecision {
        val healthRatio = enemyHealth.toFloat() / enemyMaxHealth.coerceAtLeast(1)
        val shieldRatio = enemyShield.toFloat() / enemyMaxShield.coerceAtLeast(1)
        
        val proximity = when {
            proximityDistance <= 1 -> CombatProximity.MELEE_CLOSE
            proximityDistance <= 3 -> CombatProximity.MEDIUM_RANGE
            else -> CombatProximity.LONG_RANGE
        }

        // 1. CRITICAL HEALTH RECOVERY CHECK: If health < 30% and random trigger or low shield, attempt HEAL or FORTIFY
        if (healthRatio < 0.30f) {
            val roll = Random.nextInt(100)
            if (roll < 65) {
                val repairAmount = (enemyMaxHealth * 0.25f).toInt().coerceAtLeast(12)
                return EnemyAIDecision(
                    actionType = EnemyActionType.HEAL,
                    actionName = "Emergency Core Patch",
                    healAmount = repairAmount,
                    logMessage = "🛠️ EMERGENCY CORE REPAIR: Enemy executed self-healing diagnostic routine (+${repairAmount} HP)!"
                )
            }
        }

        // 2. FORTIFY ICE CHECK: If shields completely depleted
        if (shieldRatio <= 0.0f && Random.nextInt(100) < 50) {
            val shieldRebuild = (enemyMaxShield * 0.5f).toInt().coerceAtLeast(15)
            return EnemyAIDecision(
                actionType = EnemyActionType.FORTIFY_ICE,
                actionName = "ICE Firewall Reboot",
                shieldAmount = shieldRebuild,
                logMessage = "🛡️ ICE REBOOT: Hostile system re-established ${shieldRebuild} shield integrity!"
            )
        }

        // 3. PROXIMITY & STRATEGY SELECTION
        return when (proximity) {
            CombatProximity.MELEE_CLOSE -> {
                // Close range: High physical attack bias, occasional RAM hack
                val roll = Random.nextInt(100)
                if (roll < 70) {
                    val dmg = enemyBaseDamage + Random.nextInt(-2, 5)
                    EnemyAIDecision(
                        actionType = EnemyActionType.ATTACK,
                        actionName = "Kinetic Sub-Laser Strike",
                        damage = max(4, dmg),
                        logMessage = "🚨 CLOSE-RANGE IMPACT: Hostile unleashed Kinetic Strike dealing ${max(4, dmg)} damage!"
                    )
                } else {
                    val hackDmg = (enemyBaseDamage * 0.8f).toInt()
                    val drainedRam = if (playerRam > 2) 3 else 1
                    EnemyAIDecision(
                        actionType = EnemyActionType.HACK_PLAYER,
                        actionName = "Neural Overload Exploit",
                        damage = hackDmg,
                        ramDrain = drainedRam,
                        logMessage = "⚡ NEURAL HACK: Cyber-exploit penetrated player neural deck dealing $hackDmg damage & draining $drainedRam MB RAM!"
                    )
                }
            }

            CombatProximity.MEDIUM_RANGE -> {
                // Medium range: Balanced hack vs attack
                val roll = Random.nextInt(100)
                if (roll < 50) {
                    val hackDmg = enemyBaseDamage + Random.nextInt(0, 4)
                    val drainedRam = if (playerRam > 0) 2 else 0
                    EnemyAIDecision(
                        actionType = EnemyActionType.HACK_PLAYER,
                        actionName = "DDoS Packet Stream",
                        damage = hackDmg,
                        ramDrain = drainedRam,
                        logMessage = "🌐 PACKET STREAM HACK: Target flooded network buffer for $hackDmg digital damage!"
                    )
                } else {
                    val dmg = enemyBaseDamage + Random.nextInt(-1, 3)
                    EnemyAIDecision(
                        actionType = EnemyActionType.ATTACK,
                        actionName = "Plasma Railgun Burst",
                        damage = max(3, dmg),
                        logMessage = "🎯 MEDIUM-RANGE BURST: Hostile targeted player systems dealing $dmg damage!"
                    )
                }
            }

            CombatProximity.LONG_RANGE -> {
                // Long range: Preference for hacking and ICE buffer
                val roll = Random.nextInt(100)
                if (roll < 60) {
                    val hackDmg = (enemyBaseDamage * 0.9f).toInt() + Random.nextInt(1, 4)
                    EnemyAIDecision(
                        actionType = EnemyActionType.HACK_PLAYER,
                        actionName = "Long-Range Trojan Buffer Overflow",
                        damage = hackDmg,
                        ramDrain = 2,
                        logMessage = "🛰️ REMOTE TROJAN HACK: Long-range exploit payload transmitted ($hackDmg damage)!"
                    )
                } else {
                    val shieldBoost = 10
                    EnemyAIDecision(
                        actionType = EnemyActionType.FORTIFY_ICE,
                        actionName = "Long-Range Signal Modulation",
                        shieldAmount = shieldBoost,
                        logMessage = "📡 SIGNAL MODULATION: Enemy reinforced ICE shield +$shieldBoost!"
                    )
                }
            }
        }
    }
}
