package com.example.data

import kotlin.math.max
import kotlin.math.min
import kotlin.random.Random

/**
 * Enemy combat action type generated by the AI decision script.
 */
enum class EnemyActionType {
    ATTACK,       // Direct attack on player
    HEAL,         // Repair core integrity / shield recovery when health is critical
    HACK_PLAYER,  // Cyber-exploit draining player RAM and damaging shields
    FORTIFY_ICE   // Rebuild ICE shield firewall
}

/**
 * Proximity classification between enemy unit and player runner.
 */
enum class CombatProximity {
    MELEE_CLOSE,   // Distance 1: High chance of heavy physical attack or close range hack
    MEDIUM_RANGE,  // Distance 2-3: Balanced tactical distance for hacks & ranged attacks
    LONG_RANGE     // Distance 4+: Long range hacks, ICE fortification, or repair
}

/**
 * Decision payload output from the AI behavior script.
 */
data class EnemyAIDecision(
    val actionType: EnemyActionType,
    val actionName: String,
    val damage: Int = 0,
    val healAmount: Int = 0,
    val shieldAmount: Int = 0,
    val ramDrain: Int = 0,
    val logMessage: String = ""
)

/**
 * AI behavior script for the turn-based combat system.
 * Evaluates enemy health ratio, shield integrity, player RAM vulnerability,
 * and combat proximity to dynamically select optimal tactical actions.
 */
object EnemyCombatAIScript {

    /**
     * Determines combat decision based on current health, proximity distance, and player status.
     *
     * @param enemyHealth Current enemy health points
     * @param enemyMaxHealth Maximum enemy health points
     * @param enemyShield Current enemy shield points
     * @param enemyMaxShield Maximum enemy shield points
     * @param enemyBaseDamage Base damage capability of enemy
     * @param playerHealth Current player health points
     * @param playerRam Current player available RAM
     * @param proximityDistance Sub-grid distance between enemy and player (default 1)
     */
    fun evaluateAction(
        enemyHealth: Int,
        enemyMaxHealth: Int,
        enemyShield: Int,
        enemyMaxShield: Int,
        enemyBaseDamage: Int,
        playerHealth: Int,
        playerRam: Int,
        proximityDistance: Int = 1
    ): EnemyAIDecision {
        val healthRatio = enemyHealth.toFloat() / enemyMaxHealth.coerceAtLeast(1)
        val shieldRatio = enemyShield.toFloat() / enemyMaxShield.coerceAtLeast(1)
        
        val proximity = when {
            proximityDistance <= 1 -> CombatProximity.MELEE_CLOSE
            proximityDistance <= 3 -> CombatProximity.MEDIUM_RANGE
            else -> CombatProximity.LONG_RANGE
        }

        // 1. CRITICAL HEALTH RECOVERY CHECK: If health < 30% and random trigger or low shield, attempt HEAL or FORTIFY
        if (healthRatio < 0.30f) {
            val roll = Random.nextInt(100)
            if (roll < 65) {
                val repairAmount = (enemyMaxHealth * 0.25f).toInt().coerceAtLeast(12)
                return EnemyAIDecision(
                    actionType = EnemyActionType.HEAL,
                    actionName = "Emergency Core Patch",
                    healAmount = repairAmount,
                    logMessage = "🛠️ EMERGENCY CORE REPAIR: Enemy executed self-healing diagnostic routine (+${repairAmount} HP)!"
                )
            }
        }

        // 2. FORTIFY ICE CHECK: If shields completely depleted
        if (shieldRatio <= 0.0f && Random.nextInt(100) < 50) {
            val shieldRebuild = (enemyMaxShield * 0.5f).toInt().coerceAtLeast(15)
            return EnemyAIDecision(
                actionType = EnemyActionType.FORTIFY_ICE,
                actionName = "ICE Firewall Reboot",
                shieldAmount = shieldRebuild,
                logMessage = "🛡️ ICE REBOOT: Hostile system re-established ${shieldRebuild} shield integrity!"
            )
        }

        // 3. PROXIMITY & STRATEGY SELECTION
        return when (proximity) {
            CombatProximity.MELEE_CLOSE -> {
                // Close range: High physical attack bias, occasional RAM hack
                val roll = Random.nextInt(100)
                if (roll < 70) {
                    val dmg = enemyBaseDamage + Random.nextInt(-2, 5)
                    EnemyAIDecision(
                        actionType = EnemyActionType.ATTACK,
                        actionName = "Kinetic Sub-Laser Strike",
                        damage = max(4, dmg),
                        logMessage = "🚨 CLOSE-RANGE IMPACT: Hostile unleashed Kinetic Strike dealing ${max(4, dmg)} damage!"
                    )
                } else {
                    val hackDmg = (enemyBaseDamage * 0.8f).toInt()
                    val drainedRam = if (playerRam > 2) 3 else 1
                    EnemyAIDecision(
                        actionType = EnemyActionType.HACK_PLAYER,
                        actionName = "Neural Overload Exploit",
                        damage = hackDmg,
                        ramDrain = drainedRam,
                        logMessage = "⚡ NEURAL HACK: Cyber-exploit penetrated player neural deck dealing $hackDmg damage & draining $drainedRam MB RAM!"
                    )
                }
            }

            CombatProximity.MEDIUM_RANGE -> {
                // Medium range: Balanced hack vs attack
                val roll = Random.nextInt(100)
                if (roll < 50) {
                    val hackDmg = enemyBaseDamage + Random.nextInt(0, 4)
                    val drainedRam = if (playerRam > 0) 2 else 0
                    EnemyAIDecision(
                        actionType = EnemyActionType.HACK_PLAYER,
                        actionName = "DDoS Packet Stream",
                        damage = hackDmg,
                        ramDrain = drainedRam,
                        logMessage = "🌐 PACKET STREAM HACK: Target flooded network buffer for $hackDmg digital damage!"
                    )
                } else {
                    val dmg = enemyBaseDamage + Random.nextInt(-1, 3)
                    EnemyAIDecision(
                        actionType = EnemyActionType.ATTACK,
                        actionName = "Plasma Railgun Burst",
                        damage = max(3, dmg),
                        logMessage = "🎯 MEDIUM-RANGE BURST: Hostile targeted player systems dealing $dmg damage!"
                    )
                }
            }

            CombatProximity.LONG_RANGE -> {
                // Long range: Preference for hacking and ICE buffer
                val roll = Random.nextInt(100)
                if (roll < 60) {
                    val hackDmg = (enemyBaseDamage * 0.9f).toInt() + Random.nextInt(1, 4)
                    EnemyAIDecision(
                        actionType = EnemyActionType.HACK_PLAYER,
                        actionName = "Long-Range Trojan Buffer Overflow",
                        damage = hackDmg,
                        ramDrain = 2,
                        logMessage = "🛰️ REMOTE TROJAN HACK: Long-range exploit payload transmitted ($hackDmg damage)!"
                    )
                } else {
                    val shieldBoost = 10
                    EnemyAIDecision(
                        actionType = EnemyActionType.FORTIFY_ICE,
                        actionName = "Long-Range Signal Modulation",
                        shieldAmount = shieldBoost,
                        logMessage = "📡 SIGNAL MODULATION: Enemy reinforced ICE shield +$shieldBoost!"
                    )
                }
            }
        }
    }
}
